# /* ----  https://github.com/JaKooLit  ---- */  #
# Commands and Apps to be executed at launch


# Permanent night shift warm tint
exec-once = $HOME/.config/hypr/scripts/NightShift.sh
# waybar is already started in configs/Startup_Apps.conf

# Force less zoomed-in monitor scale
exec-once = $HOME/.config/hypr/UserScripts/SetMonitorScale.sh
